storing logs to files

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -21,18 +21,19 @@ jobs:
         id: tests
         run: |
           test_output=$(mvn clean test -Dsuite=dummy 2>&1)
-          echo "::set-output name=test_output::$test_output"
+          echo "TEST_OUTPUT=${test_output}" >> "$GITHUB_WORKSPACE/test_output.env"
           echo "$test_output" > "$GITHUB_WORKSPACE/test_output.log"
         shell: bash
 
       - name: Extract test results
         id: extract_results
         run: |
-            tests_run_line=$(echo "${{ steps.tests.outputs.test_output }}" | grep -o "Tests run: [0-9]*, Failures: [0-9]*, Errors: [0-9]*, Skipped: [0-9]*" | head -n 1)
-            echo "::set-output name=tests_run_line::$tests_run_line"
+          source "$GITHUB_WORKSPACE/test_output.env"
+          tests_run_line=$(echo "$TEST_OUTPUT" | grep -o "Tests run: [0-9]*, Failures: [0-9]*, Errors: [0-9]*, Skipped: [0-9]*" | head -n 1 || true)
+          echo "::set-output name=tests_run_line::$tests_run_line"
         shell: bash
         continue-on-error: true
-      #      - name: Generate Test Report
+#      - name: Generate Test Report
 #        if: success() || failure()
 #        id: tests_rep
 #        run: |
@@ -42,12 +43,14 @@ jobs:
 #          echo "Test_Cases=$(echo "$test_output" | grep 'Tests:')" >> $GITHUB_OUTPUT
 #          echo "Test_Time=$(echo "$test_output" | grep 'Time: ')" >> $GITHUB_OUTPUT
       - name: Check output
-        if: always()
-        run: |
-             echo "${{ steps.extract_results.outputs.tests_run_line }}"
-      - name: Clean up
-        run: rm "$GITHUB_WORKSPACE/test_output.log"
         if: success()
+        run: |
+             echo ""${{ steps.extract_results.outputs.tests_run_line }}""
+      - name: Clean up
+        run:
+             |
+            rm "$GITHUB_WORKSPACE/test_output.log"
+            rm "$GITHUB_WORKSPACE/test_output.env"
 #      - name: Generate allure report
 #        uses: simple-elf/allure-report-action@master
 #        if: always()
