simplify, extracting result right from tests

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -24,7 +24,7 @@ jobs:
            echo 'test_output<<EOF'
            mvn clean test -Dsuite=dummy 2>&1
            echo EOF
-          } | grep 'Tests run:' >> "$GITHUB_ENV"
+          } | grep 'Tests run:' >> $GITHUB_OUTPUT
 #      - name: Unit Test
 #        id: unit_test
 #        run: |
@@ -33,19 +33,19 @@ jobs:
 #            yarn test 2>&1
 #            echo EOF
 #          } >> "$GITHUB_ENV"
-      - name: Generate Test Report
-        if: success() || failure()
-        id: tests_rep
-        run: |
-          echo "$test_output"
-          echo "Test_Suites=$(echo "$test_output" | grep 'Tests run:')" >> $GITHUB_OUTPUT
+#      - name: Generate Test Report
+#        if: success() || failure()
+#        id: tests_rep
+#        run: |
+#          echo "$test_output"
+#          echo "Test_Suites=$(echo "$test_output" | grep 'Tests run:')" >> $GITHUB_OUTPUT
 #          echo "Test_Suites=$(echo "$test_output" | grep 'Tests run:')" >> $GITHUB_OUTPUT
 #          echo "Test_Cases=$(echo "$test_output" | grep 'Tests:')" >> $GITHUB_OUTPUT
 #          echo "Test_Time=$(echo "$test_output" | grep 'Time: ')" >> $GITHUB_OUTPUT
       - name: Check output
         if: always()
         run: |
-          echo ${{ toJson(steps.tests_rep.outputs) }}
+          echo ${{join(steps.tests.outputs.*, '\n')}}
 #      - name: Generate allure report
 #        uses: simple-elf/allure-report-action@master
 #        if: always()
